# networks:
#   lafoca-network:
#     driver: bridge

services:
  # lafoca-mysql:
  #   image: mysql:8.4.0
  #   environment:
  #     MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  #   ports:
  #     - "3306:3306"
  #   networks:
  #     - lafoca-network

  lafoca-backend:
    image: lafoca/backend:1.0.0
    # command: ["/wait-for-it.sh", "lafoca-mysql:3306", "-t", "30", "--", "java", "-jar", "lafoca-backend.jar"]
    command: ["java", "-jar", "lafoca-backend.jar"]
    environment:
      DB_HOST: ${DB_HOST}
      DEFAULT_ADMIN_USER_EMAIL: ${DEFAULT_ADMIN_USER_EMAIL}
      DEFAULT_ADMIN_USER_NAME: ${DEFAULT_ADMIN_USER_NAME}
      DEFAULT_ADMIN_USER_PASSWORD: ${DEFAULT_ADMIN_USER_PASSWORD}
      LAFOCA_STORAGE_S3_CHAVE_ACESSO_SECRETA: ${LAFOCA_STORAGE_S3_CHAVE_ACESSO_SECRETA}
      LAFOCA_STORAGE_S3_ID_CHAVE_ACESSO: ${LAFOCA_STORAGE_S3_ID_CHAVE_ACESSO}
      LAFOCA_STORAGE_S3_BUCKET: ${LAFOCA_STORAGE_S3_BUCKET}
      SPRING_MAIL_PASSWORD: ${SPRING_MAIL_PASSWORD}
      SPRING_MAIL_PORT: ${SPRING_MAIL_PORT}
      SPRING_MAIL_HOST: ${SPRING_MAIL_HOST}
      LAFOCA_MAIL_SENDER: ${LAFOCA_MAIL_SENDER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_USERNAME: ${MYSQL_USERNAME}
      LAFOCA_JWT_KEYSTORE_JKS_LOCATION: ${LAFOCA_JWT_KEYSTORE_JKS_LOCATION}
      LAFOCA_JWT_KEYSTORE_KEYPAIR_ALIAS: ${LAFOCA_JWT_KEYSTORE_KEYPAIR_ALIAS}
      LAFOCA_JWT_KEYSTORE_PASSWORD: ${LAFOCA_JWT_KEYSTORE_PASSWORD} 
      LAFOCA_DATABASE_BACKUPPASS: ${LAFOCA_DATABASE_BACKUPPASS}
      LAFOCA_JWT_EXPIRESAT_OFDAYS: ${LAFOCA_JWT_EXPIRESAT_OFDAYS}
    ports:
      - "8080:8080"
    # networks:
    #   - lafoca-network
    # depends_on:
    #   - lafoca-mysql
