name: Lafoca Backend Application

on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'liberica'
          java-version: '21'
      - name: Build project
        run: mvn clean install
      - name: Login Docker Hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: Build docker image
        run: docker build -t lafocaufpa/lafocabackend .
      - name: Push image docker
        run:  docker push lafocaufpa/lafocabackend
  
  deploy: 
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull Image from docker hub
        run: docker pull lafocaufpa/lafocabackend:latest
      - name: Remove docker container
        run: docker rm -f lafocabackend
      - name: Run docker container
        run: > 
            docker run -d -p 8080:8080 -e DB_HOST=${{secrets.DB_HOST}} 
            -e DEFAULT_ADMIN_USER_EMAIL=${{secrets.DEFAULT_ADMIN_USER_EMAIL}} 
            -e DEFAULT_ADMIN_USER_NAME=${{secrets.DEFAULT_ADMIN_USER_NAME}} 
            -e DEFAULT_ADMIN_USER_PASSWORD=${{secrets.DEFAULT_ADMIN_USER_PASSWORD}} 
            -e LAFOCA_STORAGE_S3_CHAVE_ACESSO_SECRETA=${{secrets.LAFOCA_STORAGE_S3_CHAVE_ACESSO_SECRETA}} 
            -e LAFOCA_STORAGE_S3_ID_CHAVE_ACESSO=${{secrets.LAFOCA_STORAGE_S3_ID_CHAVE_ACESSO}} 
            -e LAFOCA_STORAGE_S3_BUCKET=${{secrets.LAFOCA_STORAGE_S3_BUCKET}} 
            -e SPRING_MAIL_PASSWORD=${{secrets.SPRING_MAIL_PASSWORD}} 
            -e SPRING_MAIL_PORT=${{secrets.SPRING_MAIL_PORT}} 
            -e SPRING_MAIL_HOST=${{secrets.SPRING_MAIL_HOST}} 
            -e LAFOCA_MAIL_SENDER=${{secrets.LAFOCA_MAIL_SENDER}} 
            -e MYSQL_PASSWORD=${{secrets.MYSQL_PASSWORD}} 
            -e MYSQL_USERNAME=${{secrets.MYSQL_USERNAME}} 
            -e MYSQL_DATABASE=${{secrets.MYSQL_DATABASE}} 
            -e LAFOCA_JWT_KEYSTORE_KEYPAIR_ALIAS=${{secrets.LAFOCA_JWT_KEYSTORE_KEYPAIR_ALIAS}} 
            -e LAFOCA_JWT_KEYSTORE_PASSWORD=${{secrets.LAFOCA_JWT_KEYSTORE_PASSWORD}} 
            -e LAFOCA_DATABASE_BACKUPPASS=${{secrets.LAFOCA_DATABASE_BACKUPPASS}} 
            -e LAFOCA_JWT_EXPIRESAT_OFDAYS=${{secrets.LAFOCA_JWT_EXPIRESAT_OFDAYS}} 
            --name lafocabackend lafocaufpa/lafocabackend
